spring:
  application:
    name: study
#  resources:
#    static-locations: classpath:/static/
  datasource:
    url: jdbc:log4jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 6022
#    driver-class-name: org.postgresql.Driver
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    # HikariCP 연결 풀 설정
    hikari:
      pool-name: HikariCP
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      max-lifetime: 600000

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.pkr.project.user.model
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl				